"""upgrades

Revision ID: 32223b460dfa
Revises: f5cfb762578c
Create Date: 2019-10-02 15:27:50.256158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32223b460dfa'
down_revision = 'f5cfb762578c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('password_safe', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'password_safe')
    # ### end Alembic commands ###
