"""contined migrations

Revision ID: 74c9ddb91701
Revises: d23485013982
Create Date: 2019-10-05 21:45:19.247092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c9ddb91701'
down_revision = 'd23485013982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('validationStatus', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_relation'), 'relationships', ['relation'], unique=True)
    op.create_table('streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('initals', sa.String(length=4), nullable=True),
    sa.Column('reg_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streams_initals'), 'streams', ['initals'], unique=True)
    op.create_index(op.f('ix_streams_name'), 'streams', ['name'], unique=True)
    op.create_table('subjectCategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=250), nullable=True),
    sa.Column('initials', sa.String(length=205), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('validation_status', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjectCategories_category'), 'subjectCategories', ['category'], unique=True)
    op.create_index(op.f('ix_subjectCategories_initials'), 'subjectCategories', ['initials'], unique=True)
    op.create_table('phoneNumber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phoneNumber_phone'), 'phoneNumber', ['phone'], unique=True)
    op.add_column('parents', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('parents', sa.Column('firstName', sa.String(length=55), nullable=True))
    op.add_column('parents', sa.Column('lastName', sa.String(length=55), nullable=True))
    op.add_column('parents', sa.Column('password', sa.String(length=30), nullable=True))
    op.add_column('parents', sa.Column('surName', sa.String(length=55), nullable=True))
    op.create_index(op.f('ix_parents_email'), 'parents', ['email'], unique=True)
    op.drop_column('parents', 'names')
    op.add_column('students', sa.Column('reg_date', sa.String(), nullable=True))
    op.add_column('subjects', sa.Column('initials', sa.String(), nullable=True))
    op.add_column('subjects', sa.Column('validationStatus', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_subjects_initials'), 'subjects', ['initials'], unique=True)
    op.create_index(op.f('ix_subjects_subject'), 'subjects', ['subject'], unique=True)
    op.drop_constraint('subjects_subject_key', 'subjects', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('subjects_subject_key', 'subjects', ['subject'])
    op.drop_index(op.f('ix_subjects_subject'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_initials'), table_name='subjects')
    op.drop_column('subjects', 'validationStatus')
    op.drop_column('subjects', 'initials')
    op.drop_column('students', 'reg_date')
    op.add_column('parents', sa.Column('names', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_parents_email'), table_name='parents')
    op.drop_column('parents', 'surName')
    op.drop_column('parents', 'password')
    op.drop_column('parents', 'lastName')
    op.drop_column('parents', 'firstName')
    op.drop_column('parents', 'email')
    op.drop_index(op.f('ix_phoneNumber_phone'), table_name='phoneNumber')
    op.drop_table('phoneNumber')
    op.drop_index(op.f('ix_subjectCategories_initials'), table_name='subjectCategories')
    op.drop_index(op.f('ix_subjectCategories_category'), table_name='subjectCategories')
    op.drop_table('subjectCategories')
    op.drop_index(op.f('ix_streams_name'), table_name='streams')
    op.drop_index(op.f('ix_streams_initals'), table_name='streams')
    op.drop_table('streams')
    op.drop_index(op.f('ix_relationships_relation'), table_name='relationships')
    op.drop_table('relationships')
    # ### end Alembic commands ###
