"""current 11:21am

Revision ID: 94277a221b4b
Revises: 9e864f39b747
Create Date: 2019-10-09 11:21:15.922069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94277a221b4b'
down_revision = '9e864f39b747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_detail', sa.String(length=100), nullable=True),
    sa.Column('role_description', sa.String(length=300), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.Column('activation_status', sa.String(length=300), nullable=True),
    sa.Column('time_stamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_role_detail'), 'roles', ['role_detail'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_role_detail'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
