"""current 2:22pm

Revision ID: 9e864f39b747
Revises: 74c9ddb91701
Create Date: 2019-10-08 14:21:41.158707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e864f39b747'
down_revision = '74c9ddb91701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('password_secure', sa.String(length=30), nullable=True))
    op.drop_column('parents', 'password')
    op.add_column('streams', sa.Column('valid', sa.Boolean(), nullable=True))
    op.add_column('streams', sa.Column('validation_status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streams', 'validation_status')
    op.drop_column('streams', 'valid')
    op.add_column('parents', sa.Column('password', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('parents', 'password_secure')
    # ### end Alembic commands ###
