"""upgrades2tll

Revision ID: b828d052c3f3
Revises: 32223b460dfa
Create Date: 2019-10-02 15:44:15.107947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b828d052c3f3'
down_revision = '32223b460dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('teachers', 'password_safe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('password_safe', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('teachers', 'pass_secure')
    # ### end Alembic commands ###
