"""current 6:39pm

Revision ID: bba83295806f
Revises: 94277a221b4b
Create Date: 2019-10-09 18:39:09.786699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba83295806f'
down_revision = '94277a221b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenity_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('validation_status', sa.String(length=200), nullable=True),
    sa.Column('time_stamp', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenity_categories_category'), 'amenity_categories', ['category'], unique=True)
    op.create_table('school_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('category_initials', sa.String(length=50), nullable=True),
    sa.Column('category_desc', sa.String(length=300), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('validation_status', sa.String(length=200), nullable=True),
    sa.Column('time_stamp', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('category_initials')
    )
    op.create_table('school_students_gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('gender_initials', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('validation_status', sa.String(length=200), nullable=True),
    sa.Column('time_stamp', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_students_gender_gender'), 'school_students_gender', ['gender'], unique=True)
    op.create_index(op.f('ix_school_students_gender_gender_initials'), 'school_students_gender', ['gender_initials'], unique=True)
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amenity', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('validation_status', sa.String(length=200), nullable=True),
    sa.Column('time_stamp', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['amenity_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenities_amenity'), 'amenities', ['amenity'], unique=True)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('school_initials', sa.String(length=50), nullable=True),
    sa.Column('school_motto', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('time_stamp', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['school_categories.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['school_students_gender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('amenity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('teachers', sa.Column('portal_handle', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'portal_handle')
    op.drop_table('school_amenities')
    op.drop_table('schools')
    op.drop_index(op.f('ix_amenities_amenity'), table_name='amenities')
    op.drop_table('amenities')
    op.drop_index(op.f('ix_school_students_gender_gender_initials'), table_name='school_students_gender')
    op.drop_index(op.f('ix_school_students_gender_gender'), table_name='school_students_gender')
    op.drop_table('school_students_gender')
    op.drop_table('school_categories')
    op.drop_index(op.f('ix_amenity_categories_category'), table_name='amenity_categories')
    op.drop_table('amenity_categories')
    # ### end Alembic commands ###
