"""kaput on sch_test

Revision ID: c1951661ce0a
Revises: bba83295806f
Create Date: 2019-10-12 13:36:52.496387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1951661ce0a'
down_revision = 'bba83295806f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sch_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sch_name', sa.String(length=25), nullable=True),
    sa.Column('sch_motto', sa.String(length=300), nullable=True),
    sa.Column('time_stamp', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sch_test')
    # ### end Alembic commands ###
