"""continous migration

Revision ID: d23485013982
Revises: b828d052c3f3
Create Date: 2019-10-04 20:12:40.786287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23485013982'
down_revision = 'b828d052c3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('reg_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'reg_date')
    # ### end Alembic commands ###
